require('user.init')

-- TODO: Tutorial - complete the todolist bellow

-- TODO: Press space to see the keymapping or go to lua/user/keymapping.lua, press <space>ff to locate that file.

-- TODO: change theme
-- User.luadev = false
-- User.theme.colorscheme = 'kanagawa' -- tokyonight, solarized
-- User.theme.lualine = 'bubbles' -- default, evil_lualine, bubbles, slanted
-- User.theme.sidebar = 'bottom' -- right, left, bottom, toplevel

-- TODO: Change lualine colors, to see the available pallets to go lua/theme/colors.lua
-- User.theme.lualine_colors = {
--   bg = '#16161D',
--   fg = '#C8C093',
--   yellow = '#938056',
--   cyan = '#6A9589',
--   darkblue = '#7E9CD8',
--   green = '#98c379',
--   orange = '#FFA066',
--   violet = '#938AA9',
--   magenta = '#D16D9E',
--   blue = '#658594',
--   red = '#E82424',
--   grey = '#54546D',
-- }

-- TODO: pick your programm langs to improve hignlighting
-- User.langs = {
--   'bash',
--   'c',
--   'c_sharp',
--   'cpp',
--   'css',
--   'dart',
--   'fish',
--   'go',
--   'graphql',
--   'html',
--   'java',
--   'javascript',
--   'json',
--   'kotlin',
--   'lua',
--   'markdown',
--   'php',
--   'prisma',
--   'python',
--   'regex',
--   'scss',
--   'svelte',
--   'tsx',
--   'typescript',
--   'vim',
--   'vue',
--   'yaml',
-- }
--
-- TODO: pick your formatters to use, to see more options go to lua/user/formatting.lua
-- User.formatting = {
--   'prettier',
--   'stylua',
-- }

-- TODO: pick your diagnostics to use, to see more options go to lua/user/diagnostics.lua
-- User.diagnostics = {
--   'eslint',
-- }

-- TODO: pick your servers to use, to see more options go to lua/user/server.lua
-- User.servers = {
--   'pylsp',
--   'tsserver',
--   'sumneko_lua',
--   'prismals',
--   'graphql',
--   'jdtls',
--   'cssls',
--   'html',
--   'vuels',
--   'volar',
--   'emmet_ls',
--   'tailwindcss',
--   'svelte',
-- }

-- TODO: Add more plugins, docs: https://github.com/wbthomason/packer.nvim
-- User.plugins = {
--   'justinmk/vim-sneak',
--   'rebelot/kanagawa.nvim',
-- }
