local plugins_folder = 'lib.plugins.'

pcall(function()
  require(plugins_folder .. 'autopairs')
  require(plugins_folder .. 'autotag')
  require(plugins_folder .. 'bufferline')
  require(plugins_folder .. 'cmp')
  require(plugins_folder .. 'colorizer')
  require(plugins_folder .. 'comment')
  require(plugins_folder .. 'dashboard')
  require(plugins_folder .. 'diffview')
  require(plugins_folder .. 'gitsigns')
  require(plugins_folder .. 'lsp_signature')
  require(plugins_folder .. 'lsp')
  require(plugins_folder .. 'lspsaga')
  require(plugins_folder .. 'lualine')
  require(plugins_folder .. 'null-ls')
  require(plugins_folder .. 'shade')
  require(plugins_folder .. 'telescope')
  require(plugins_folder .. 'toggleterm')
  require(plugins_folder .. 'tree')
  require(plugins_folder .. 'treesitter')
  require(plugins_folder .. 'which-key')
end)
