return {
  {
    'olimorris/onedarkpro.nvim',
    lazy = false,
    priority = 1000,
    -- commit = '89b919f6904e441bf450cf0ae0c40c4410a2d875',
    config = function()
      require('onedarkpro').setup {
        colors = {
          bglight = '#3a404c',
          bgdark = '#1e2127',
          bgdarker = '#1a1e22',
        },
        styles = {
          comments = 'italic',
          keywords = 'italic',
          functions = 'italic',
          variables = 'italic',
          conditionals = 'italic',
        },
        highlights = {
          HopNextKey = { fg = '${purple}', bg = 'NONE', extend = true },
          HopNextKey1 = { fg = '${blue}', bg = 'NONE', extend = true },
          CmpItemKindText = { reverse = true, extend = true },
          CmpItemKindMethod = { reverse = true, extend = true },
          CmpItemKindFunction = { reverse = true, extend = true },
          CmpItemKindConstructor = { reverse = true, extend = true },
          CmpItemKindField = { reverse = true, extend = true },
          CmpItemKindVariable = { reverse = true, extend = true },
          CmpItemKindClass = { reverse = true, extend = true },
          CmpItemKindInterface = { reverse = true, extend = true },
          CmpItemKindModule = { reverse = true, extend = true },
          CmpItemKindProperty = { reverse = true, extend = true },
          CmpItemKindUnit = { reverse = true, extend = true },
          CmpItemKindValue = { reverse = true, extend = true },
          CmpItemKindEnum = { reverse = true, extend = true },
          CmpItemKindKeyword = { reverse = true, extend = true },
          CmpItemKindSnippet = { reverse = true, extend = true },
          CmpItemKindColor = { reverse = true, extend = true },
          CmpItemKindFile = { reverse = true, extend = true },
          CmpItemKindReference = { reverse = true, extend = true },
          CmpItemKindFolder = { reverse = true, extend = true },
          CmpItemKindEnumMember = { reverse = true, extend = true },
          CmpItemKindConstant = { reverse = true, extend = true },
          CmpItemKindStruct = { reverse = true, extend = true },
          CmpItemKindEvent = { reverse = true, extend = true },
          CmpItemKindOperator = { reverse = true, extend = true },
          CmpItemKindTypeParameter = { reverse = true, extend = true },
          DashboardHeader = { fg = '${comment}', extend = true },
          DashboardCenter = { fg = '${fg}', extend = true },
          DashboardFooter = { fg = '${comment}', extend = true },
          DashboardProjectTitle = { link = 'Title' },
          DashboardProjectTitleIcon = { link = 'Title' },
          DashboardProjectIcon = { fg = '${purple}', extend = true },
          DashboardMruTitle = { link = 'Title' },
          DashboardMruIcon = { link = 'Title' },
          DashboardFiles = { fg = '${fg}', extend = true },
          DashboardShotCutIcon = { fg = '${blue}', extend = true },
          DashboardDesc = { fg = '${blue}', extend = true },
          DashboardKey = { fg = '${purple}', extend = true },
          DashboardIcon = { fg = '${blue}', extend = true },
          DashboardShotCut = { fg = '${purple}', extend = true },
          ColorColumn = { fg = '${float_bg}', bg = '${float_bg}' },
          NvimTreeNormal = { bg = '${float_bg}', extend = true },
          NvimTreeNormalNC = { link = 'NvimTreeNormal' },
          NvimTreeWinSeparator = { fg = '${float_bg}', bg = '${float_bg}', extend = true },
          ['@function.builtin'] = { link = '@function' },
          PMenuSel = { fg = '${blue}', reverse = true, extend = true },
          PmenuThumb = { bg = '${purple}', extend = true },
          CmpWinSeparator = { fg = '${float_bg}', bg = '${float_bg}', extend = true },
          WinSeparator = { bg = '${float_bg}', extend = true },
          TelescopeBorder = { fg = '${float_bg}', bg = '${float_bg}', extend = true },
          TelescopeResultsNormal = { bg = '${bgdark}', extend = true },
          TelescopeResultsBorder = { fg = '${bgdark}', bg = '${bgdark}', extend = true },
          TelescopePreviewNormal = { bg = '${bgdarker}', extend = true },
          TelescopePreviewBorder = { fg = '${bgdarker}', bg = '${bgdarker}', extend = true },
          TelescopePromptTitle = { fg = '${purple}', extend = true },
          TelescopeResultsTitle = { fg = '${green}', extend = true },
          TelescopePreviewTitle = { fg = '${blue}', extend = true },
          IblScope = { fg = '${purple}' },
        },
      }

      vim.cmd.colorscheme 'onedark'
    end,
  },
}
